a = int(input("Enter first number: "))
b = int(input("enter second number: "))
#print(int(a%b))
#print(type(a))
#c = (a>b)
#print("a is greater than b is:",c)
#c = int((a+b)/2)
#print("the average of the two numbers is :",c)
#print(type(c#))

#d =int(b*b)
print("the square of first number is :",c)
#print("the square of second number is :",d)
#print(type(c))
#print(type(d))  